
### Create User

POST http://localhost:5001/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email" : "jhondoe212@gmail.com",
    "fullName": "Jhon Doe",
    "password": "123458d4"
}


### Login User

POST  http://localhost:5001/api/auth/login HTTP/1.1
content-type: application/json

{
    "email" : "jhondoe212@gmail.com",
     "password": "123458d4"
}


### Logout User

POST http://localhost:5001/api/auth/logout HTTP/1.1


### Send Message To User


POST http://localhost:5001/api/messages/send/68e6d7b4f6ea87c70f459420 HTTP/1.1
Content-Type: application/json

{
    "text" : "Bye"
}


### Get Messages For User

GET http://localhost:5001/api/messages/68e6d7b4f6ea87c70f459420 HTTP/1.1


### Get Users For Sidebar

GET http://localhost:5001/api/messages/68e6d7b4f6ea87c70f459420 HTTP/1.1
